# Generated by Django 4.2.11 on 2024-03-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBike', models.CharField(max_length=255)),
                ('content', models.TextField(default='')),
                ('price', models.PositiveSmallIntegerField(default=1)),
                ('year', models.PositiveSmallIntegerField(default=1800)),
                ('imgBike', models.ImageField(blank=True, null=True, upload_to='mediabike')),
            ],
        ),
        migrations.DeleteModel(
            name='ListCars',
        ),
    ]
